---
id: Service_Weather
name: Service_Weather
full: Weather service library
description: >-
  A library that provide an abstraction to various online weather service
  providers. Includes drivers for WeatherUnderground and WorldWeatherOnline.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Service_Weather
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Date: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Url: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
