---
id: Service_Weather
name: Service_Weather
full: Weather service library
description: >-
  A library that provide an abstraction to various online weather service
  providers. Includes drivers for WeatherUnderground and WorldWeatherOnline.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Service_Weather
authors:
  - name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 3.0.0-RC1
  api: 3.0.0alpha1
state:
  release: RC
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^8.1
    composer:
      horde/date: ^3
      horde/exception: ^3
      horde/translation: ^3
      horde/url: ^3
      psr/http-client: ^1
      psr/http-factory: ^1
      psr/http-message: ^1 || ^2
      psr/simple-cache: ^3
  optional:
    composer:
      horde/db: ^3
      horde/http: ^3.1.0
      horde/test: ^3
vendor: horde
keywords: null
ci-platform:
  '8.1':
    - php: ^8.1
    - composer-plugin-api: ^2.2.0
    - ext-dom
  '8.2':
    - php: ^8.2
    - composer-plugin-api: ^2.2.0
    - ext-dom
  '8.3':
    - php: ^8.3
    - composer-plugin-api: ^2.2.0
    - ext-dom
  '8.4':
    - php: ^8.4
    - composer-plugin-api: ^2.2.0
    - ext-dom
  '8.5':
    - php: ^8.5
    - composer-plugin-api: ^2.2.0
    - ext-dom
  '8.6':
    - php: ^8.6
    - composer-plugin-api: ^2.2.0
    - ext-dom
ci-platform-flags:
  needs_installer_plugin: false
